apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-frontend
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      containers:
      - name: hotel-frontend
        image: parcibalnomas/hotel-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32725
  selector:
    app: hotel-frontend